### ISSUE TITLE
本人の許可をもらっていない

### ISSUE THREAD

**Issue by eyemono-moe** [detteiu8383/long-nekoppi-fill-space#1]
https://github.com/detteiu8383/long-nekoppi-fill-space/blob/739d68d67bff2bd51c0101c691846afa3bd462d6/README.md?plain=1#L4

**Comment by junjiruw** [comment]
飼い主です。本猫は意思疎通が不可能なので許可を取るのは難しいと思います

.　^____^
（三⦿ω⦿三）！！！！！！！！！！！！！
